version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo # TZ TimeZone sempre America/Sao_Paulo
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional pois depende da rede que está usando...
    volumes:
      - C:\trabalhos\jellyfin\config
      - C:\trabalhos\jellyfin\musicas
      - C:\trabalhos\jellyfin\filmes
      - C:\trabalhos\jellyfin\seriados
    ports:
      - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    restart: unless-stopped